// package caching provides generic Firebase functionality.

package fsutils

import (
	"Assignment2/util"
	"cloud.google.com/go/firestore"
	"context"
	"firebase.google.com/go"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"log"
)

// NewFirestoreContext initializes a new context and a Firestore cLient in a Config struct
func NewFirestoreContext(config *util.Config, configFilePath string) error {

	config.FirestoreClient = new(firestore.Client)
	config.Ctx = new(context.Context)

	*config.Ctx = context.Background()

	// Load service account credentials:
	serviceAccount := option.WithCredentialsFile(configFilePath)
	app, err := firebase.NewApp(*config.Ctx, nil, serviceAccount)
	if err != nil {
		log.Println("unable to create new caching app")
		return err
	}
	// Instantiate caching client
	config.FirestoreClient, err = app.Firestore(*config.Ctx)
	if err != nil {
		log.Println("unable to instantiate firestore client")
		return err
	}
	return nil
}

// Close closes the Firestore client
func Close(config *util.Config) error {
	return config.FirestoreClient.Close()
}

// AddDocument stores a new document in a Firestore collection (by name).
// Returns autogenerated document ID.
func AddDocument(config *util.Config, collection string, data interface{}) (string, error) {
	id, _, err := config.FirestoreClient.Collection(collection).Add(*config.Ctx, data)
	if err != nil {
		return "", err
	}
	return id.ID, nil
}

// AddDocumentById stores a new document with specified id in a
// Firestore collection.
// Overwrites existing document if document with id already exists.
func AddDocumentById(config *util.Config, collection string, id string, document interface{}) error {
	_, err := config.FirestoreClient.Collection(collection).Doc(id).Set(*config.Ctx, document)
	return err
}

// DeleteDocument deletes document with a specific id from a collection.
func DeleteDocument(config *util.Config, collection, id string) error {
	_, err := config.FirestoreClient.Collection(collection).Doc(id).Delete(*config.Ctx)
	return err
}

// ReadDocument reads a specific document by id.
func ReadDocument(config *util.Config, collection, id string) (map[string]interface{}, error) {
	documentSnap, err := config.FirestoreClient.Collection(collection).Doc(id).Get(*config.Ctx)
	if err != nil {
		return nil, err
	}
	document := documentSnap.Data()
	return document, nil
}

// ReadDocumentGeneral reads a specific document into a predefined struct.
func ReadDocumentGeneral(config *util.Config, collection, id string, document interface{}) error {
	documentSnap, err := config.FirestoreClient.Collection(collection).Doc(id).Get(*config.Ctx)
	if err != nil {
		return err
	}
	err = documentSnap.DataTo(document)
	return err
}

// CountDocuments counts all docs in specified collection.
func CountDocuments(config *util.Config, collection string) (int, error) {
	count := 0
	iter := config.FirestoreClient.Collection(collection).Documents(*config.Ctx)

	for {
		_, err := iter.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return 0, err
		}
		count++
	}
	return count, nil
}
