services:
  #name of service (in Docker context):
  renewables:

    # build based on "Dockerfile" in current dir:
    build: 
      context: .
      dockerfile: Dockerfile2

    # mount volumes located in VM on container(s):
    volumes:
      # credentials:
      # mounts as original cmd directory
      - /home/ubuntu/.secret:/cmd/:ro
    
    # port mapping (remote:local)
    ports:
      - '8080:10000'

    # restart service at VM reboot:
    restart: always

